enableScripts: true
nodeLinker: node-modules
npmScopes:
  murakai:
    npmRegistryServer: https://git.mreichelt.dev/git-manager/~npm/
    npmPublishRegistry: https://git.mreichelt.dev/git-manager/~npm/
    npmAuthToken: ${NPM_TOKEN}