approvedGitRepositories:
  - "**"

enableScripts: true

injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  git-manager:
    npmAuthToken: "${NPM_TOKEN}"
    npmPublishRegistry: "https://git.mreichelt.dev/git-manager/~npm/"
    npmRegistryServer: "https://git.mreichelt.dev/git-manager/~npm/"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
