approvedGitRepositories:
  - "**"

enableScripts: true

injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  murakai:
    npmAuthToken: "${NPM_TOKEN}"
    npmPublishRegistry: "https://git.mreichelt.dev/git-manager/~npm/"
    npmRegistryServer: "https://git.mreichelt.dev/git-manager/~npm/"
